"""initial_schema

Revision ID: d38ec98a08fe
Revises: 
Create Date: 2026-09-05 08:49:08.110143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd38ec98a08fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_id'), ['id'], unique=False)

    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hazard_level', sa.String(length=20), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('default_unit', sa.String(length=20), nullable=True),
    sa.Column('base_market_price_min', sa.Float(), nullable=False),
    sa.Column('base_market_price_max', sa.Float(), nullable=False),
    sa.Column('current_benchmark_price', sa.Float(), nullable=False),
    sa.Column('recoverable_materials', sa.JSON(), nullable=True),
    sa.Column('icon_name', sa.String(length=50), nullable=True),
    sa.Column('safety_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_materials_id'), ['id'], unique=False)

    op.create_table('safety_guides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('danger_description', sa.Text(), nullable=False),
    sa.Column('safe_practice_description', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('material_category', sa.String(length=100), nullable=False),
    sa.Column('hazard_type', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('pictorial_icon', sa.String(length=100), nullable=True),
    sa.Column('dos', sa.JSON(), nullable=True),
    sa.Column('donts', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safety_guides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safety_guides_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_safety_guides_language'), ['language'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    op.create_table('collectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('total_earnings', sa.Float(), nullable=True),
    sa.Column('total_weight_collected', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('collectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collectors_id'), ['id'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('buying_price', sa.Float(), nullable=True),
    sa.Column('benchmark_price', sa.Float(), nullable=False),
    sa.Column('market_min', sa.Float(), nullable=False),
    sa.Column('market_max', sa.Float(), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('location_city', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_history_material_id'), ['material_id'], unique=False)

    op.create_table('recyclers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('facility_name', sa.String(length=255), nullable=False),
    sa.Column('authorization_status', sa.String(length=50), nullable=True),
    sa.Column('authorization_number', sa.String(length=100), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('accepted_materials', sa.JSON(), nullable=True),
    sa.Column('service_radius_km', sa.Float(), nullable=True),
    sa.Column('pickup_available', sa.Boolean(), nullable=True),
    sa.Column('pickup_min_weight_kg', sa.Float(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authorization_number'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('recyclers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recyclers_id'), ['id'], unique=False)

    op.create_table('e_waste_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.String(length=50), nullable=False),
    sa.Column('trace_id', sa.String(length=50), nullable=False),
    sa.Column('collector_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('material_name', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('estimated_weight', sa.Float(), nullable=False),
    sa.Column('final_weight', sa.Float(), nullable=True),
    sa.Column('estimated_price_min', sa.Float(), nullable=False),
    sa.Column('estimated_price_max', sa.Float(), nullable=False),
    sa.Column('recommended_price', sa.Float(), nullable=False),
    sa.Column('quoted_price', sa.Float(), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('condition', sa.String(length=100), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('location_address', sa.String(length=500), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('qr_code_url', sa.String(length=500), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('hazard_level', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collector_id'], ['collectors.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('e_waste_lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_e_waste_lots_collector_id'), ['collector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_e_waste_lots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_e_waste_lots_lot_id'), ['lot_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_e_waste_lots_trace_id'), ['trace_id'], unique=True)

    op.create_table('recycler_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recycler_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('price_per_unit', sa.Float(), nullable=True),
    sa.Column('offer_price_per_kg', sa.Float(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('min_weight_kg', sa.Float(), nullable=True),
    sa.Column('pickup_available', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['recycler_id'], ['recyclers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recycler_offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recycler_offers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recycler_offers_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recycler_offers_recycler_id'), ['recycler_id'], unique=False)

    op.create_table('ai_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prediction_type', sa.String(length=50), nullable=True),
    sa.Column('predicted_category', sa.String(length=100), nullable=True),
    sa.Column('detected_category', sa.String(length=100), nullable=False),
    sa.Column('detected_subcategory', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('estimated_weight', sa.Float(), nullable=False),
    sa.Column('estimated_value_min', sa.Float(), nullable=True),
    sa.Column('estimated_value_max', sa.Float(), nullable=True),
    sa.Column('value_min', sa.Float(), nullable=False),
    sa.Column('value_max', sa.Float(), nullable=False),
    sa.Column('hazard_level', sa.String(length=20), nullable=True),
    sa.Column('recoverable_metals', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['e_waste_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_predictions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_predictions_lot_id'), ['lot_id'], unique=False)

    op.create_table('trace_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['e_waste_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trace_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trace_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trace_events_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trace_events_trace_id'), ['trace_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('collector_id', sa.Integer(), nullable=False),
    sa.Column('recycler_id', sa.Integer(), nullable=False),
    sa.Column('quoted_price', sa.Float(), nullable=True),
    sa.Column('agreed_price_per_kg', sa.Float(), nullable=False),
    sa.Column('final_weight', sa.Float(), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('transaction_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_ref', sa.String(length=100), nullable=True),
    sa.Column('scheduled_pickup_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collector_id'], ['collectors.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['e_waste_lots.id'], ),
    sa.ForeignKeyConstraint(['recycler_id'], ['recyclers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_collector_id'), ['collector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_recycler_id'), ['recycler_id'], unique=False)

    op.create_table('anomaly_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('benchmark_value', sa.Float(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=False),
    sa.Column('deviation_pct', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['e_waste_lots.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anomaly_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anomaly_alerts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_alerts_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_alerts_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('handover_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('initial_weight', sa.Float(), nullable=True),
    sa.Column('final_weight', sa.Float(), nullable=False),
    sa.Column('verified_weight', sa.Float(), nullable=False),
    sa.Column('weight_discrepancy_pct', sa.Float(), nullable=True),
    sa.Column('final_rate_per_kg', sa.Float(), nullable=False),
    sa.Column('final_price', sa.Float(), nullable=False),
    sa.Column('final_amount_paid', sa.Float(), nullable=False),
    sa.Column('handover_photo', sa.String(length=500), nullable=True),
    sa.Column('photo_proof_url', sa.String(length=500), nullable=True),
    sa.Column('handover_timestamp', sa.DateTime(), nullable=True),
    sa.Column('recycler_digital_signature', sa.String(length=255), nullable=True),
    sa.Column('collector_confirmation', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    with op.batch_alter_table('handover_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_handover_records_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('handover_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_handover_records_id'))

    op.drop_table('handover_records')
    with op.batch_alter_table('anomaly_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anomaly_alerts_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_anomaly_alerts_lot_id'))
        batch_op.drop_index(batch_op.f('ix_anomaly_alerts_id'))

    op.drop_table('anomaly_alerts')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_recycler_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_collector_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('trace_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trace_events_trace_id'))
        batch_op.drop_index(batch_op.f('ix_trace_events_lot_id'))
        batch_op.drop_index(batch_op.f('ix_trace_events_id'))

    op.drop_table('trace_events')
    with op.batch_alter_table('ai_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_predictions_lot_id'))
        batch_op.drop_index(batch_op.f('ix_ai_predictions_id'))

    op.drop_table('ai_predictions')
    with op.batch_alter_table('recycler_offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recycler_offers_recycler_id'))
        batch_op.drop_index(batch_op.f('ix_recycler_offers_material_id'))
        batch_op.drop_index(batch_op.f('ix_recycler_offers_id'))

    op.drop_table('recycler_offers')
    with op.batch_alter_table('e_waste_lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_e_waste_lots_trace_id'))
        batch_op.drop_index(batch_op.f('ix_e_waste_lots_lot_id'))
        batch_op.drop_index(batch_op.f('ix_e_waste_lots_id'))
        batch_op.drop_index(batch_op.f('ix_e_waste_lots_collector_id'))

    op.drop_table('e_waste_lots')
    with op.batch_alter_table('recyclers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recyclers_id'))

    op.drop_table('recyclers')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_material_id'))
        batch_op.drop_index(batch_op.f('ix_price_history_id'))

    op.drop_table('price_history')
    with op.batch_alter_table('collectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collectors_id'))

    op.drop_table('collectors')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('safety_guides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safety_guides_language'))
        batch_op.drop_index(batch_op.f('ix_safety_guides_id'))

    op.drop_table('safety_guides')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_id'))
        batch_op.drop_index(batch_op.f('ix_materials_code'))
        batch_op.drop_index(batch_op.f('ix_materials_category'))

    op.drop_table('materials')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_id'))
        batch_op.drop_index(batch_op.f('ix_locations_city'))

    op.drop_table('locations')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
